loading libraries

diff --git a/rsd b/rsd
--- a/rsd
+++ b/rsd
@@ -24,12 +24,13 @@
 #   2 - Bad usage
 #   3 - Command not found
 #   4 - There is a new version in the repository
-#   5 - No rsd.lib
+#   5 - Missing
 #   6 - Missing system files (maybe not installed)
 #   7 - Mismatch information
 #   8 - To be done in the future
 #   9 - Missing command line argument
 #   10 - Command failure (unknown reason)
+#   11 - Internal Failure
 
 RSD_VERSION='0.2.1'
 VERSION=$RSD_VERSION
@@ -54,7 +55,7 @@ RSD_BASE=""
 RSD=$(basename $0)
 
 if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
-    echo "BASH >= 4 required.  Got $BASH_VESION"
+    echo "Abort! BASH >= 4 required.  Got $BASH_VESION"
     exit 1
 fi
 
@@ -155,12 +156,12 @@ function rsd::parse_args() {
         case "$1" in
         --*)
             arg=${1:2}
-            if rsd::key_exists $arg in RSD_ARGS_PARAM; then
+            if bash::key_exists $arg in RSD_ARGS_PARAM; then
                 if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
                     RSD_ARGS[${arg,,}]=1
                 else
                     if [[ -z $2 ]]; then
-                        echo "Missing argumento to $arg."
+                        echo "Abort! Missing argumento to $arg."
                         exit 9
                     fi
                     RSD_ARGS[${arg,,}]=$2
@@ -173,12 +174,12 @@ function rsd::parse_args() {
             ;;
         -*)
             arg=${1:1}
-            if rsd::key_exists $arg in RSD_ARGS_PARAM; then
+            if bash::key_exists $arg in RSD_ARGS_PARAM; then
                 if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
                     RSD_ARGS[${arg,,}]=1
                 else
                     if [[ -z $2 ]]; then
-                        echo "Missing argumento to $arg."
+                        echo "Abort! Missing argumento to $arg."
                         exit 9
                     fi
                     RSD_ARGS[${arg,,}]=$2
@@ -211,11 +212,12 @@ function rsd::parse_args() {
     return 0
 }
 
-function rsd::key_exists() {
-    if [[ "$2" != in ]]; then
-        echo "Incorrect usage."
-        echo "Correct usage: rsd::key_exists {key} in {array}"
-        return 1
+# from bash_extensions.lib
+function bash::key_exists(){
+    if [[ "$2" != "in" ]]; then
+        echo "Abort! Incorrect usage of bash::key_exists."
+        echo "Correct usage: bash::key_exists {key} in {array}"
+        exit 11
     fi
     eval '[ ${'$3'[$1]+muahaha} ]'
 }
@@ -303,7 +305,7 @@ rsd::debug2 9 "Arguments parsed (values): keys -> (${RSD_ARGS[@]}): " ${!RSD_ARG
 rsd::debug "Original call was $RSD_ORIGINAL_ARGS" 7
 
 if ! rsd::get_base; then
-    echo "Could not find libdir.  Maybe it need to be installed --install (TODO)."
+    echo "Abort! Could not find libdir.  Maybe it need to be installed --install (TODO)."
     exit 5
 fi
 
@@ -330,9 +332,28 @@ fi
 # check version
 if [[ ${RSD_ARGS[install]} ]]; then
     rsd::check_binaries_or_fail git
-    echo "Installing latest rsd from repository"
+    echo "Installing latest rsd from repository."
     git clone --depth 1 $RSD_GITHUB_REPO ${RSD_ARGS[install]}
 fi
+
+# load our main library
+# after this point there is a need to the full installation
+#Now load our defaults
+source "$RSD_BASE/lib/rsd.lib"
+
+if [[ -f "$RSD_BASE/lib/bash_extensions.lib" ]]; then
+    source "$RSD_BASE/lib/bash_extensions.lib"
+else
+    echo "Abort! Missing bash extensions library."
+    exit 5
+fi
+
+
+if [[ -z "${RSD_ARGS[command]}" ]]; then
+    echo "Abort! No COMMAND specified."
+    usage
+fi
+RSD_COMMAND=${RSD_ARGS[command]}
 
 
 
