rsd::parse_args  Now accepts named parameters

diff --git a/rsd b/rsd
--- a/rsd
+++ b/rsd
@@ -79,7 +79,6 @@ fi
 
 shopt -s extglob
 
-declare -A RSD_ARGS=( ["subargs"]="" ["command"]="" )
 # paramenters arguments
 # 0 => No argument
 # 1 => One argument
@@ -227,74 +226,86 @@ function rsd::check_binaries_or_fail() {
 	return 0
 }
 
-# for debug, it has to be done in the script, command line does not work so soon
-# TODO: make an exception if the argument does not exist
+# Parse command line arguments
+# - First argument is the name of the Associative Array with the configuration
+# - The second argument is the name of the Associative Array to be used as a return
+#   it will be created globally
 function rsd::parse_args() {
-	local arg
+	local config=$1
+	shift
+	local param=$1
+	shift
+	local tempConfig tempParam arg 
 	local count=0
+	
+	eval "unset $param"
+	eval "declare  -gA $param"
 
 	rsd::debug2 8 "rsd::parse_args: Total: $#, Arguments:" $@
-	rsd::debug2 8 "rsd::parse_args: RSD_ARGS subargs: " ${RSD_ARGS["subargs"]}
-
-	RSD_ARGS["subargs"]=
 
 	while [ $# -gt 0 ]; do
 		case "$1" in
 		--*)
-		arg=${1:2}
-		if bash::key_exists $arg in RSD_ARGS_PARAM; then
-			if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-			RSD_ARGS[${arg,,}]=1
+			arg=${1:2}
+			tempConfig=$config[$arg]
+			tempParam=$param[${arg,,}]
+			
+			# Note: can't use a variable variable in assignment as 
+			#       ${!tempParam}=$2
+			#       so we use eval
+
+			if bash::key_exists $arg in RSD_ARGS_PARAM; then
+				if [[ "${!tempConfig}" == "0" ]]; then
+					eval "$tempParam=1"
+				else
+					if [[ -z $2 ]]; then
+						rsd::warn "Abort! Missing argumento to $arg."
+						exit 9
+					fi	
+						eval "$tempParam=$2"
+					shift
+				fi
 			else
-			if [[ -z $2 ]]; then
-				rsd::warn "Abort! Missing argumento to $arg."
-				exit 9
+				eval "$tempParam=$2"
+				shift
 			fi
-			RSD_ARGS[${arg,,}]=$2
-			shift
-			fi
-		else
-			RSD_ARGS[${arg,,}]=$2
-			shift
-		fi
+
 		;;
 		-*)
-		arg=${1:1}
-		if bash::key_exists $arg in RSD_ARGS_PARAM; then
-			if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-			RSD_ARGS[${arg,,}]=1
+			arg=${1:1}
+			tempConfig=$config[$arg]
+			tempParam=$param[${arg,,}]
+			if bash::key_exists $arg in RSD_ARGS_PARAM; then
+				if [[ "${!tempConfig}" == "0" ]]; then
+					eval "$tempParam=1"
+				else
+					if [[ -z $2 ]]; then
+						rsd::warn "Abort! Missing argumento to $arg."
+						exit 9
+					fi
+					eval "$tempParam=$2"
+					shift
+				fi
 			else
-			if [[ -z $2 ]]; then
-				rsd::warn "Abort! Missing argumento to $arg."
-				exit 9
+				eval "$tempParam=$2"
+				shift
 			fi
-			RSD_ARGS[${arg,,}]=$2
-			shift
-			fi
-		else
-			RSD_ARGS[${arg,,}]=$2
-			shift
-		fi
 		;;
 		*)
-		if ((count == 1)); then
-			RSD_ARGS["subargs"]=$*
-			shift
-			break
-		fi
-		RSD_ARGS["command"]=$1
+			if ((count == 1)); then
+				tempParam=$param[subargs]
+				eval "$tempParam=\$*"
+				shift
+				break
+			fi
+			tempParam=$param[command]
+			eval "$tempParam=$1"
 
-		((count++))
+			((count++))
 		;;
 		esac
 		shift
 	done
-
-	local key
-	for key in ${!RSD_ARGS[@]}; do
-		rsd::debug2 8 "parse_agrs: arguments: $key: ${RSD_ARGS[$key]}"
-	done
-
 	return 0
 }
 
@@ -374,7 +385,7 @@ function rsd::check_libdir_file() {
 # FIXME: as a recursive command calling, this is worked outside a function (for now at least)
 
 RSD_ORIGINAL_ARGS="$0 $@"
-rsd::parse_args $*
+rsd::parse_args RSD_ARGS_PARAM RSD_ARGS $*
 
 # import rsd::debug level
 if   [[ ${RSD_ARGS[debug]} ]]; then
