Change indentation and add version check
* Change script identiation to 4 spaces (instead of the ugly 2).
* --check-version option to compare to the one in the repository.

diff --git a/rsd b/rsd
--- a/rsd
+++ b/rsd
@@ -12,17 +12,21 @@
 #   1 - Not bash 4
 #   2 - Bad usage
 #   3 - Command not found
+#   4 - There is a new version in the repository
 #   5 - No rsd.lib
 #   6 - Missing system files (maybe not installed)
 #   7 - Mismatch information
 #   8 - To be done in the future
 #   10 - Command failure (unknown reason)
 
-RSD_VERSION='0.2.0'
+RSD_VERSION='0.2.1'
 VERSION=$RSD_VERSION
 
 RSD_DEBUG=0
 DEBUG=$RSD_DEBUG
+
+# The latest version of this file in the repository url
+RSD_LATEST_RSD_REPO="https://raw.githubusercontent.com/rsd/rsd/master/rsd"
 
 # preserves arguments
 RSD_ORIGINAL_ARGS="$0 $@"
@@ -37,155 +41,175 @@ RSD_BASE=""
 RSD=$(basename $0)
 
 if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
-  echo "BASH >= 4 required.  Got $BASH_VESION"
-  exit 1
+    echo "BASH >= 4 required.  Got $BASH_VESION"
+    exit 1
 fi
 
 shopt -s extglob
 
-declare -A RSD_ARGS=( ["subargs"]="" ["command"]="")
+declare -A RSD_ARGS=( ["subargs"]="" ["command"]="" )
 # paramenters arguments
 # 0 => No argument
 # 1 => One argument
 # unknown defaults to 1
-declare -A RSD_ARGS_PARAM=( ["debug"]=1 ["d"]=1 ["version"]=0 )
+declare -A RSD_ARGS_PARAM=( ["debug"]=1 ["d"]=1 ["version"]=0 ["check-version"]=0 )
 
 
 function rsd::version_gt() {
-  test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
+    test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
 }
 
 function rsd::usage() {
-  echo "$RSD v$RSD_VERSION"
-  echo "Usage:"
-  echo -e "\t$RSD <command> [OPTIONS]"
-  echo -e "\tCommands:"
+    echo "$RSD v$RSD_VERSION"
+    echo "Usage:"
+    echo -e "\t$RSD <command> [OPTIONS]"
+    echo -e "\tCommands:"
 
-  exit 2
-}
+    exit 2
+    }
 
 function rsd::debug() {
-  local msg=$1
-  shift
-  local level=1
+    local msg=$1
+    shift
+    local level=1
 
-  if (($#>0));then
-    level=$1
-  fi
-  if (( $RSD_DEBUG >= $level )); then
-    echo "$level:$msg"
-  fi
+    if (($#>0));then
+        level=$1
+    fi
+    if (( $RSD_DEBUG >= $level )); then
+        echo "$level:$msg"
+    fi
 }
 
 #same as rsd::debug, but the level comes first, for convenience
 function rsd::debug2() {
-  local level=$1
-  shift
+    local level=$1
+    shift
 
-  if (( $RSD_DEBUG >= $level )); then
-    echo "$level:" $@
-  fi
+    if (( $RSD_DEBUG >= $level )); then
+        echo "$level:" $@
+    fi
 }
 
 #Finds a file in the path
 function rsd::check_binary() {
-  local file=$1
-  local path
-  local IFS=":"
+    local file=$1
+    local path
+    local IFS=":"
 
-  for path in $PATH; do
-    if [[ -f "$path/$file" ]]; then
-      return 0
-    fi
-  done
+    for path in $PATH; do
+        if [[ -f "$path/$file" ]]; then
+            return 0
+        fi
+    done
 
-  RSD_ERROR_MSG="Command $file not in PATH."
-  return 1
+    RSD_ERROR_MSG="Command $file not in PATH."
+    return 1
 }
 
 function rsd::check_binaries() {
-  local file
-  local path
-  local IFS=":"
+    local file
+    local path
+    local IFS=":"
 
-  for file in $*;  do
-    if ! rsd::check_binary $file; then
-      return 1
-    fi
-  done
-  return 0
+    for file in $*;  do
+        if ! rsd::check_binary $file; then
+            return 1
+        fi
+    done
+    return 0
 }
 
 function rsd::check_binaries_or_fail() {
-  if ! rsd::check_binaries $@; then
-	echo $RSD_ERROR_MSG
-	exit 3
-  fi
-  return 0
+    if ! rsd::check_binaries $@; then
+        echo $RSD_ERROR_MSG
+        exit 3
+    fi
+    return 0
 }
 
 
 function rsd::parse_args() {
-  local arg
-  local count=0
+    local arg
+    local count=0
 
-  rsd::debug2 8 "rsd::parse_args: Total: $#, Arguments:" $@
-  rsd::debug2 8 "rsd::parse_args: RSD_ARGS subargs: " ${RSD_ARGS["subargs"]}
+    rsd::debug2 8 "rsd::parse_args: Total: $#, Arguments:" $@
+    rsd::debug2 8 "rsd::parse_args: RSD_ARGS subargs: " ${RSD_ARGS["subargs"]}
 
-  RSD_ARGS["subargs"]=
+    RSD_ARGS["subargs"]=
 
-  while [ $# -gt 0 ]; do
-    case "$1" in
-      --*)
-        arg=${1:2}
-        if rsd::key_exists $arg in RSD_ARGS_PARAM; then
-          if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-            RSD_ARGS[${arg,,}]=1
-          else
-            RSD_ARGS[${arg,,}]=$2
-            shift
-          fi
-        else
-          RSD_ARGS[${arg,,}]=$2
-          shift
-        fi
-        ;;
-      -*)
-        arg=${1:1}
-        if rsd::key_exists $arg in RSD_ARGS_PARAM; then
-          if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-            RSD_ARGS[${arg,,}]=1
-          else
-            RSD_ARGS[${arg,,}]=$2
-            shift
-          fi
-        else
-          RSD_ARGS[${arg,,}]=$2
-          shift
-        fi
-        ;;
-      *)
-        if ((count == 1)); then
-          RSD_ARGS["subargs"]=$*
-          shift
-          break
-        fi
-        RSD_ARGS["command"]=$1
+    while [ $# -gt 0 ]; do
+        case "$1" in
+        --*)
+            arg=${1:2}
+            if rsd::key_exists $arg in RSD_ARGS_PARAM; then
+                if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
+                    RSD_ARGS[${arg,,}]=1
+                else
+                    RSD_ARGS[${arg,,}]=$2
+                    shift
+                fi
+            else
+                RSD_ARGS[${arg,,}]=$2
+                shift
+            fi
+            ;;
+        -*)
+            arg=${1:1}
+            if rsd::key_exists $arg in RSD_ARGS_PARAM; then
+                if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
+                    RSD_ARGS[${arg,,}]=1
+                else
+                    RSD_ARGS[${arg,,}]=$2
+                    shift
+                fi
+            else
+                RSD_ARGS[${arg,,}]=$2
+                shift
+            fi
+            ;;
+        *)
+            if ((count == 1)); then
+                RSD_ARGS["subargs"]=$*
+                shift
+                break
+            fi
+            RSD_ARGS["command"]=$1
 
-        ((count++))
-        ;;
-    esac
-    shift
-  done
+            ((count++))
+            ;;
+        esac
+        shift
+    done
 }
 
 function rsd::key_exists() {
-  if [[ "$2" != in ]]; then
-    echo "Incorrect usage."
-    echo "Correct usage: rsd::key_exists {key} in {array}"
-    return 1
-  fi
-  eval '[ ${'$3'[$1]+muahaha} ]'
+    if [[ "$2" != in ]]; then
+        echo "Incorrect usage."
+        echo "Correct usage: rsd::key_exists {key} in {array}"
+        return 1
+    fi
+    eval '[ ${'$3'[$1]+muahaha} ]'
+}
+
+# check the latest version in the repository
+function rsd::check_repository_version() {
+    local repo_version
+    rsd::check_binaries_or_fail wget grep head
+
+    repo_version=$(wget -q -O - $RSD_LATEST_RSD_REPO | grep ^RSD_VERSION= \
+                  | head -n 1 | sed -e "s/.*=['\"]\(.*\)['\"]/\1/")
+
+    if rsd::version_gt $repo_version $RSD_VERSION; then
+        RSD_ERROR_MSG="There is a newes version in the repository: $repo_version.  Our version: $RSD_VERSION."
+        return 1
+    elif [[ $repo_version == $RSD_VERSION ]]; then
+        RSD_ERROR_MSG="You are using the latest version: $RSD_VERSION."
+    else
+        RSD_ERROR_MSG="Your version: $RSD_VERSION is newer that the one in the repository: $repo_version."
+    fi
+
+    return 0
 }
 
 # __main__
@@ -194,10 +218,10 @@ function rsd::key_exists() {
 rsd::parse_args $*
 
 # import rsd::debug level
-if   [[ ${RSD_ARGS["debug"]} ]]; then
-	RSD_DEBUG=${RSD_ARGS["debug"]}
+if   [[ ${RSD_ARGS[debug]} ]]; then
+    RSD_DEBUG=${RSD_ARGS[debug]}
 elif [[ ${RSD_ARGS[d]} ]]    ; then
-	RSD_DEBUG=${RSD_ARGS[d]}
+    RSD_DEBUG=${RSD_ARGS[d]}
 fi
 rsd::debug "Debug set to $RSD_DEBUG" 2
 rsd::debug2 9 "Arguments parsed (values): keys -> (${RSD_ARGS[@]}): " ${!RSD_ARGS[@]}
@@ -205,8 +229,20 @@ rsd::debug "Original call was $RSD_ORIGINAL_ARGS" 7
 
 # version
 if [[ ${RSD_ARGS[version]} ]]; then
-  echo $RSD_VERSION
-  exit 0
+    echo $RSD_VERSION
+    exit 0
+fi
+
+# check version
+if [[ ${RSD_ARGS[check-version]} ]]; then
+    if ! rsd::check_repository_version; then
+        echo $RSD_ERROR_MSG
+        exit 4
+    else
+        echo $RSD_ERROR_MSG
+        exit 0
+    fi
+
 fi
 
 # FIXME: for now
