replace spaces for tabs identation

diff --git a/rsd b/rsd
--- a/rsd
+++ b/rsd
@@ -65,8 +65,8 @@ RSD_RUN_DIR=$(readlink -f $(dirname $0))
 RSD_LOCAL_DIR=$(pwd)
 
 if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
-    echo "Abort! BASH >= 4 required.  Got $BASH_VESION" >&2
-    exit 1
+	echo "Abort! BASH >= 4 required.  Got $BASH_VESION" >&2
+	exit 1
 fi
 
 shopt -s extglob
@@ -77,222 +77,222 @@ declare -A RSD_ARGS=( ["subargs"]="" ["command"]="" )
 # 1 => One argument
 # unknown defaults to 1
 declare -A RSD_ARGS_PARAM=( ["debug"]=1 ["d"]=1 ["version"]=0 ["check-version"]=0 \
-                            ["lib-dir"]=1 ["l"]=1 ["install"]=1 ["no-local"]=0 \
-                            ["nl"]=0 ["usage"]=0 ["help"]=0 ["h"]=0 \
-                            ["rsdlib"]=0 ["completion"]=0 )
+			["lib-dir"]=1 ["l"]=1 ["install"]=1 ["no-local"]=0 \
+			["nl"]=0 ["usage"]=0 ["help"]=0 ["h"]=0 \
+			["rsdlib"]=0 ["completion"]=0 )
 
 function rsd::version_gt() {
-    test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
+	test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
 }
 
 function rsd::usage() {
-    local command
+	local command
 
-    echo "$RSD v$RSD_VERSION"
-    echo "Usage:"
-    if [[ -z "$RSD_COMMAND" ]]; then
-        echo -e "\t$RSD [RSD OPTIONS] <command> "
-        if bash::is_function rsd::list_all_commands; then
-            echo -e "\tCommands:"
-            for command in $(rsd::list_all_commands); do
-                echo -e "\t\t$command"
-            done
-        fi
-    else
-        if bash::is_function rsd::list_all_actions; then
-            echo -e "\t$RSD [RSD OPTIONS] $RSD_COMMAND <action> [COMMAND OPTIONS]"
-            echo -e "\tActions for $RSD_COMMAND:"
-            rsd::list_all_actions $RSD_COMMAND
-        else
-            echo -e "\t$RSD [RSD OPTIONS] <command> "
-        fi
-    fi
-    exit 2
+	echo "$RSD v$RSD_VERSION"
+	echo "Usage:"
+	if [[ -z "$RSD_COMMAND" ]]; then
+		echo -e "\t$RSD [RSD OPTIONS] <command> "
+		if bash::is_function rsd::list_all_commands; then
+		echo -e "\tCommands:"
+		for command in $(rsd::list_all_commands); do
+			echo -e "\t\t$command"
+		done
+		fi
+	else
+		if bash::is_function rsd::list_all_actions; then
+		echo -e "\t$RSD [RSD OPTIONS] $RSD_COMMAND <action> [COMMAND OPTIONS]"
+		echo -e "\tActions for $RSD_COMMAND:"
+		rsd::list_all_actions $RSD_COMMAND
+		else
+		echo -e "\t$RSD [RSD OPTIONS] <command> "
+		fi
+	fi
+	exit 2
 }
 
 function rsd::debug() {
-    local msg=$1
-    shift
-    local level=1
+	local msg=$1
+	shift
+	local level=1
 
-    if (($#>0));then
-        level=$1
-    fi
-    if (( $RSD_DEBUG >= $level )); then
-        echo "$level:$msg"
-    fi
+	if (($#>0));then
+		level=$1
+	fi
+	if (( $RSD_DEBUG >= $level )); then
+		echo "$level:$msg"
+	fi
 }
 
 #same as rsd::debug, but the level comes first, for convenience
 function rsd::debug2() {
-    local level=$1
-    shift
+	local level=$1
+	shift
 
-    if (( $RSD_DEBUG >= $level )); then
-        echo "$level:" $@
-    fi
+	if (( $RSD_DEBUG >= $level )); then
+		echo "$level:" $@
+	fi
 }
 
 # same as rsd::debug, but to STDERR
 function rsd::warn() {
-    local msg=$1
-    shift
-    local level=1
+	local msg=$1
+	shift
+	local level=1
 
-    if (($#>0));then
-        level=$1
-    fi
-    if (( $RSD_DEBUG >= $level )); then
-        echo "$level:$msg" >&2
-    fi
+	if (($#>0));then
+		level=$1
+	fi
+	if (( $RSD_DEBUG >= $level )); then
+		echo "$level:$msg" >&2
+	fi
 }
 
 # same as rsd::debug2, but to STDERR
 function rsd::warn2() {
-    local level=$1
-    shift
+	local level=$1
+	shift
 
-    if (( $RSD_DEBUG >= $level )); then
-        echo "$level:" $@ >&2
-    fi
+	if (( $RSD_DEBUG >= $level )); then
+		echo "$level:" $@ >&2
+	fi
 }
 
 #Finds a file in the path
 function rsd::check_binary() {
-    local file=$1
-    local path
-    local IFS=":"
+	local file=$1
+	local path
+	local IFS=":"
 
-    for path in $PATH; do
-        if [[ -f "$path/$file" ]]; then
-            return 0
-        fi
-    done
+	for path in $PATH; do
+		if [[ -f "$path/$file" ]]; then
+		return 0
+		fi
+	done
 
-    RSD_ERROR_MSG="Command $file not in PATH."
-    return 1
+	RSD_ERROR_MSG="Command $file not in PATH."
+	return 1
 }
 
 function rsd::check_binaries() {
-    local file
-    local path
-    local IFS=":"
+	local file
+	local path
+	local IFS=":"
 
-    for file in $*;  do
-        if ! rsd::check_binary $file; then
-            return 1
-        fi
-    done
-    return 0
+	for file in $*;  do
+		if ! rsd::check_binary $file; then
+		return 1
+		fi
+	done
+	return 0
 }
 
 function rsd::check_binaries_or_fail() {
-    if ! rsd::check_binaries $@; then
-        rsd::warn $RSD_ERROR_MSG
-        exit 3
-    fi
-    return 0
+	if ! rsd::check_binaries $@; then
+		rsd::warn $RSD_ERROR_MSG
+		exit 3
+	fi
+	return 0
 }
 
 # for debug, it has to be done in the script, command line does not work so soon
 # TODO: make an exception if the argument does not exist
 function rsd::parse_args() {
-    local arg
-    local count=0
+	local arg
+	local count=0
 
-    rsd::debug2 8 "rsd::parse_args: Total: $#, Arguments:" $@
-    rsd::debug2 8 "rsd::parse_args: RSD_ARGS subargs: " ${RSD_ARGS["subargs"]}
+	rsd::debug2 8 "rsd::parse_args: Total: $#, Arguments:" $@
+	rsd::debug2 8 "rsd::parse_args: RSD_ARGS subargs: " ${RSD_ARGS["subargs"]}
 
-    RSD_ARGS["subargs"]=
+	RSD_ARGS["subargs"]=
 
-    while [ $# -gt 0 ]; do
-        case "$1" in
-        --*)
-            arg=${1:2}
-            if bash::key_exists $arg in RSD_ARGS_PARAM; then
-                if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-                    RSD_ARGS[${arg,,}]=1
-                else
-                    if [[ -z $2 ]]; then
-                        rsd::warn "Abort! Missing argumento to $arg."
-                        exit 9
-                    fi
-                    RSD_ARGS[${arg,,}]=$2
-                    shift
-                fi
-            else
-                RSD_ARGS[${arg,,}]=$2
-                shift
-            fi
-            ;;
-        -*)
-            arg=${1:1}
-            if bash::key_exists $arg in RSD_ARGS_PARAM; then
-                if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
-                    RSD_ARGS[${arg,,}]=1
-                else
-                    if [[ -z $2 ]]; then
-                        rsd::warn "Abort! Missing argumento to $arg."
-                        exit 9
-                    fi
-                    RSD_ARGS[${arg,,}]=$2
-                    shift
-                fi
-            else
-                RSD_ARGS[${arg,,}]=$2
-                shift
-            fi
-            ;;
-        *)
-            if ((count == 1)); then
-                RSD_ARGS["subargs"]=$*
-                shift
-                break
-            fi
-            RSD_ARGS["command"]=$1
+	while [ $# -gt 0 ]; do
+		case "$1" in
+		--*)
+		arg=${1:2}
+		if bash::key_exists $arg in RSD_ARGS_PARAM; then
+			if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
+			RSD_ARGS[${arg,,}]=1
+			else
+			if [[ -z $2 ]]; then
+				rsd::warn "Abort! Missing argumento to $arg."
+				exit 9
+			fi
+			RSD_ARGS[${arg,,}]=$2
+			shift
+			fi
+		else
+			RSD_ARGS[${arg,,}]=$2
+			shift
+		fi
+		;;
+		-*)
+		arg=${1:1}
+		if bash::key_exists $arg in RSD_ARGS_PARAM; then
+			if [[ "${RSD_ARGS_PARAM[$arg]}" == "0" ]]; then
+			RSD_ARGS[${arg,,}]=1
+			else
+			if [[ -z $2 ]]; then
+				rsd::warn "Abort! Missing argumento to $arg."
+				exit 9
+			fi
+			RSD_ARGS[${arg,,}]=$2
+			shift
+			fi
+		else
+			RSD_ARGS[${arg,,}]=$2
+			shift
+		fi
+		;;
+		*)
+		if ((count == 1)); then
+			RSD_ARGS["subargs"]=$*
+			shift
+			break
+		fi
+		RSD_ARGS["command"]=$1
 
-            ((count++))
-            ;;
-        esac
-        shift
-    done
+		((count++))
+		;;
+		esac
+		shift
+	done
 
-    local key
-    for key in ${!RSD_ARGS[@]}; do
-        rsd::debug2 8 "parse_agrs: arguments: $key: ${RSD_ARGS[$key]}"
-    done
+	local key
+	for key in ${!RSD_ARGS[@]}; do
+		rsd::debug2 8 "parse_agrs: arguments: $key: ${RSD_ARGS[$key]}"
+	done
 
-    return 0
+	return 0
 }
 
 # from bash_extensions.lib
 function bash::key_exists() {
-    if [[ "$2" != "in" ]]; then
-        rsd::warn "Abort! Incorrect usage of bash::key_exists."
-        rsd::warn "Correct usage: bash::key_exists {key} in {array}"
-        exit 11
-    fi
-    eval '[ ${'$3'[$1]+muahaha} ]'
+	if [[ "$2" != "in" ]]; then
+		rsd::warn "Abort! Incorrect usage of bash::key_exists."
+		rsd::warn "Correct usage: bash::key_exists {key} in {array}"
+		exit 11
+	fi
+	eval '[ ${'$3'[$1]+muahaha} ]'
 }
 
 # check the latest version in the repository
 function rsd::check_repository_version() {
-    local repo_version
-    rsd::check_binaries_or_fail wget grep head
+	local repo_version
+	rsd::check_binaries_or_fail wget grep head
 
-    repo_version=$(wget -q -O - $RSD_LATEST_RSD_REPO | grep ^RSD_VERSION= \
-                  | head -n 1 | sed -e "s/.*=['\"]\(.*\)['\"]/\1/")
+	repo_version=$(wget -q -O - $RSD_LATEST_RSD_REPO | grep ^RSD_VERSION= \
+			| head -n 1 | sed -e "s/.*=['\"]\(.*\)['\"]/\1/")
 
-    if rsd::version_gt $repo_version $RSD_VERSION; then
-        RSD_ERROR_MSG="There is a newes version in the repository: $repo_version.  Our version: $RSD_VERSION."
-        return 1
-    elif [[ $repo_version == $RSD_VERSION ]]; then
-        RSD_ERROR_MSG="You are using the latest version: $RSD_VERSION."
-    else
-        RSD_ERROR_MSG="Your version: $RSD_VERSION is newer that the one in the repository: $repo_version."
-    fi
+	if rsd::version_gt $repo_version $RSD_VERSION; then
+		RSD_ERROR_MSG="There is a newes version in the repository: $repo_version.  Our version: $RSD_VERSION."
+		return 1
+	elif [[ $repo_version == $RSD_VERSION ]]; then
+		RSD_ERROR_MSG="You are using the latest version: $RSD_VERSION."
+	else
+		RSD_ERROR_MSG="Your version: $RSD_VERSION is newer that the one in the repository: $repo_version."
+	fi
 
-    return 0
+	return 0
 }
 
 # Search all LIBDIRs for a file and return it on STDOUT
@@ -345,9 +345,9 @@ rsd::parse_args $*
 
 # import rsd::debug level
 if   [[ ${RSD_ARGS[debug]} ]]; then
-    RSD_DEBUG=${RSD_ARGS[debug]}
+	RSD_DEBUG=${RSD_ARGS[debug]}
 elif [[ ${RSD_ARGS[d]} ]]    ; then
-    RSD_DEBUG=${RSD_ARGS[d]}
+	RSD_DEBUG=${RSD_ARGS[d]}
 fi
 rsd::debug "Debug set to $RSD_DEBUG" 2
 rsd::debug2 9 "Arguments parsed (values): keys -> (${RSD_ARGS[@]}): " ${!RSD_ARGS[@]}
@@ -355,30 +355,30 @@ rsd::debug "Original call was $RSD_ORIGINAL_ARGS" 7
 
 # swith to a local copy if any (local == pwd)
 if ! [[ ${RSD_ARGS[no-local]} || ${RSD_ARGS[nl]} ]]; then
-    rsd::debug2 20 "RUN DIR: $RSD_RUN_DIR, LOCAL DIR: $RSD_LOCAL_DIR"
-    if [[ "$RSD_RUN_DIR" != "$RSD_LOCAL_DIR" ]]; then
-        RSD_LOCAL_RSD="$RSD_LOCAL_DIR/$RSD"
-        if [[ -x  "$RSD_LOCAL_RSD" ]]; then
-            #get version
-            RSD_LOCAL_VERSION=$( $RSD_LOCAL_RSD --version)
-            if rsd::version_gt $RSD_LOCAL_VERSION $VERSION; then
-                if [[ -z ${RSD_ARGS[completion]} ]]; then
-                    rsd::warn "Switching to local version (-nl to avoid)."
-                fi
-                $RSD_LOCAL_RSD $@
-                exit 0
-            fi
-        fi
-    fi
+	rsd::debug2 20 "RUN DIR: $RSD_RUN_DIR, LOCAL DIR: $RSD_LOCAL_DIR"
+	if [[ "$RSD_RUN_DIR" != "$RSD_LOCAL_DIR" ]]; then
+		RSD_LOCAL_RSD="$RSD_LOCAL_DIR/$RSD"
+		if [[ -x  "$RSD_LOCAL_RSD" ]]; then
+		#get version
+		RSD_LOCAL_VERSION=$( $RSD_LOCAL_RSD --version)
+		if rsd::version_gt $RSD_LOCAL_VERSION $VERSION; then
+			if [[ -z ${RSD_ARGS[completion]} ]]; then
+			rsd::warn "Switching to local version (-nl to avoid)."
+			fi
+			$RSD_LOCAL_RSD $@
+			exit 0
+		fi
+		fi
+	fi
 fi
 
 # downloads and install
 # check version
 if [[ ${RSD_ARGS[install]} ]]; then
-    rsd::check_binaries_or_fail git
-    echo "Installing latest rsd from repository."
-    git clone --depth 1 $RSD_GITHUB_REPO ${RSD_ARGS[install]}
-    exit $?
+	rsd::check_binaries_or_fail git
+	echo "Installing latest rsd from repository."
+	git clone --depth 1 $RSD_GITHUB_REPO ${RSD_ARGS[install]}
+	exit $?
 fi
 
 # Expands libdir search paths
@@ -399,31 +399,31 @@ if bash::key_exists lib in RSD_ARGS; then
 fi
 
 if ! rsd::check_libdir_file lib/rsd.lib; then
-    rsd::warn "Abort! Could not find libdir.  Maybe it need to be installed --install (TODO)."
-    exit 5
+	rsd::warn "Abort! Could not find libdir.  Maybe it need to be installed --install (TODO)."
+	exit 5
 fi
 
 # library to be loaded from outside (e.g. completion)
 if [[ -n "${RSD_ARGS[rsdlib]}" ]]; then
-    echo $(rsd::get_libdir_file lib/rsd.lib)
-    exit 0
+	echo $(rsd::get_libdir_file lib/rsd.lib)
+	exit 0
 fi
 
 # version
 if [[ ${RSD_ARGS[version]} ]]; then
-    rsd::warn $RSD_VERSION
-    exit 0
+	rsd::warn $RSD_VERSION
+	exit 0
 fi
 
 # check version
 if [[ ${RSD_ARGS[check-version]} ]]; then
-    if ! rsd::check_repository_version; then
-        rsd::warn $RSD_ERROR_MSG
-        exit 4
-    else
-        rsd::warn $RSD_ERROR_MSG
-        exit 0
-    fi
+	if ! rsd::check_repository_version; then
+		rsd::warn $RSD_ERROR_MSG
+		exit 4
+	else
+		rsd::warn $RSD_ERROR_MSG
+		exit 0
+	fi
 fi
 
 # load our main library
@@ -432,46 +432,46 @@ fi
 source $(rsd::get_libdir_file lib/rsd.lib)
 
 if rsd::check_libdir_file lib/bash_extensions.lib; then
-    source $(rsd::get_libdir_file lib/bash_extensions.lib)
+	source $(rsd::get_libdir_file lib/bash_extensions.lib)
 else
-    rsd::warn "Abort! Missing bash extensions library."
-    exit 5
+	rsd::warn "Abort! Missing bash extensions library."
+	exit 5
 fi
 
 
 
 if [[ -z "${RSD_ARGS[command]}" ]]; then
-    if ! [[ ${RSD_ARGS[completion]} ]]; then
-        rsd::usage
-    fi
+	if ! [[ ${RSD_ARGS[completion]} ]]; then
+		rsd::usage
+	fi
 fi
 
 if [[ "${RSD_ARGS[command]}" ]]; then
-    RSD_COMMAND=${RSD_ARGS[command]}
+	RSD_COMMAND=${RSD_ARGS[command]}
 
-    # import the calling command script
-    _rsd_source=$(rsd::load_command_file $RSD_COMMAND)
-    if (($?)); then
-        rsd::warn "Command $RSD_COMMAND not found"
-        rsd::usage
-    fi
+	# import the calling command script
+	_rsd_source=$(rsd::load_command_file $RSD_COMMAND)
+	if (($?)); then
+		rsd::warn "Command $RSD_COMMAND not found"
+		rsd::usage
+	fi
 
-    # sourcing the command, any argument left is passed to
-    eval $_rsd_source ${RSD_ARGS[subargs]}
+	# sourcing the command, any argument left is passed to
+	eval $_rsd_source ${RSD_ARGS[subargs]}
 fi
 
 
 # help and usage
 if [[ ${RSD_ARGS[usage]} || ${RSD_ARGS[help]} || ${RSD_ARGS[h]} ]]; then
-    rsd::usage
+	rsd::usage
 fi
 
 # execute the command function and pass the rest of the arguments
 # if there is a command function arguments are given and let it takes control
 if [[ ${RSD_ARGS[command]} ]]; then
-    if ! [[ ${RSD_ARGS[completion]} ]]; then
-        rsd::command $RSD_COMMAND
-    fi
+	if ! [[ ${RSD_ARGS[completion]} ]]; then
+		rsd::command $RSD_COMMAND
+	fi
 fi
 
 
