compatibility fixes

diff --git a/rsd b/rsd
--- a/rsd
+++ b/rsd
@@ -81,7 +81,7 @@ RSD_ON=1
 
 # Initial Debug level.  It will be replaced by command line arguments later on.
 # Set to 1 to debug stages before command line argument has a chance to kick in
-RSD_DEBUG=0
+RSD_DEBUG=1
 
 # Note: RSD will load the command file and call the command function as needed.
 #       Hoever the script needs to be self independent to download, install or upgrade itself as neeeded.
@@ -151,6 +151,11 @@ declare -A RSD_ARGS_PARAM=(
     ["config"]=1
     ["c"]=1
 )
+
+# Processed Command Line Arguments
+declare -A RSD_ARGS
+# Unprocessed Command Line Arguments
+declare -a RSD_ARGS_UNPROCESSED
 
 
 # Seatch paths
@@ -272,8 +277,7 @@ function rsd::debug2() {
 # Arguments:
 #   $1 - The message to be displayed
 function rsd::warn() {
-	local msg=$1
-    echo "Warning: $msg" >&2
+    echo "Warning: $*" >&2
 }
 
 # Finds a bin file in the path
@@ -328,7 +332,8 @@ function rsd::check_binaries_or_fail() {
 # Parse command line arguments:
 # Arguments:
 #   $1 - The name of the Associative Array with the configuration
-#   $2 - The name of the Associative Array to be used as a return
+#   $2 - The name of the Associative Array to be used as a return with processed information
+#   $3 - The name of the Array to be used as a return with non-processed information (pass-thru).
 #   $* - The command line arguments
 # Returns:
 #   Associative Array with the parsed arguments
@@ -338,16 +343,18 @@ function rsd::check_binaries_or_fail() {
 function rsd::parse_args() {
 	local config_name=$1
 	local param_name=$2
-	shift 2
+	local unprocessed_name=$3
+	shift 3
 
     declare -n config="$config_name"
-    eval "declare -gA $param_name=()"
+    declare -n param="$param_name"
+    declare -n unprocessed="$unprocessed_name"
 
 	local arg
 	local count=0
 
-    if [[ "$RSD_DEBUG" ]]; then
-        rsd::debug2 1 "rsd::parse_args: Total: $#, Arguments:" $@
+    if [[ "$RSD_DEBUG" -gt 0 ]]; then
+        rsd::warn "rsd::parse_args: Total: $#, Arguments:" "$@"
     fi
 
 	while [ $# -gt 0 ]; do
@@ -360,35 +367,27 @@ function rsd::parse_args() {
             if bash::key_exists "$arg" in config; then
                 if [[ "${config[$arg]}" -eq 1 ]]; then
                     if [[ -z $2 ]]; then
-                        echo "Error: Missing argument for option $1." >&2
+                        rsd::warn "Error: Missing argument for option $1."
                         exit 9
                     else
-                        eval "$param_name[$arg]=\"$2\""
+                        param_name[$arg]="$2"
                         shift
                     fi
                 else
-                    eval "$param_name[$arg]=1"
+                    param_name[$arg]=1
                 fi
             else
-                $ FIXME: For now
                 # Handling unrecognized options
-                echo "Error: Unrecognized option '$1'." >&2
-                exit 9
-                # Assign a non-existent flag so that COMMANDS can have it own flags
-                # TODO: Maybe just leave them as unprocessed arguments to later on be checked by the command
-#                eval "$tempParam=$2"
-#                shift
+                rsd::debug2 10 "Error: Unrecognized option '$1'."
+                unprocessed+=($1)
+                shift
             fi
             ;;
 		*)
             if [[ $count -eq 0 ]]; then
-                eval "$param_name[command]=\"$1\""
+                param_name[command]="$1"
             else
-                if [[ -z ${param[subargs]} ]]; then
-                    eval "$param_name[subargs]=\"$1\""
-                else
-                    eval "$param_name[subargs]+=\"$1\""
-                fi
+                unprocessed+=($1)
             fi
             ((count++))
             ;;
@@ -653,7 +652,7 @@ function rsd::create_search_path() {
     RSD_LIBRARY_SEARCH_PATH+=("$(dirname "${BASH_SOURCE[@]}")")
 
     # Print all paths in the array for debugging
-    printf "Library Search Paths for $RSD_MODE:\n%s\n" "${RSD_LIBRARY_SEARCH_PATH[@]}"
+    #printf "Library Search Paths for $RSD_MODE:\n%s\n" "${RSD_LIBRARY_SEARCH_PATH[@]}"
 }
 
 # __main__
@@ -662,7 +661,7 @@ function rsd::create_search_path() {
 # preserves arguments
 RSD_ORIGINAL_ARGS=("$0" "${@}")
 rsd::find_mode
-rsd::parse_args RSD_ARGS_PARAM RSD_ARGS $*
+rsd::parse_args RSD_ARGS_PARAM RSD_ARGS RSD_ARGS_UNPROCESSED $*
 
 # import rsd::debug level
 if [[ ${RSD_ARGS[debug]} ]]; then
@@ -791,9 +790,9 @@ if [[ ${RSD_ARGS[command]} ]]; then
 	    rsd::warn "GO..."
 		rsd::command $RSD_COMMAND
 	fi
+else
+	rsd::usage
 fi
-
-
 
 # FIXME: for now
 exit 0
